### PR TITLE
chore: Update argocd-vault-plugin to 1.16

### PR DESCRIPTION
**Pull request by dennislapchenko**

### CODE REVIEW

**Review by Joibel — APPROVED** [review]

**Comment by Joibel** [comment]
It hasn't noticed vault-replacer yet either, although that was only cooked recently @tico24

**Comment by dennislapchenko** [comment]
> hmm. renovate should have picked this change up automatically so I'll look into it.

i thought so too, seeing the renovate comment. 
So i double checked that there is no PR. Considering here its still 1.14 - renovate is sleeping for some time now :) 
Happy for this release, finally my change in vault plugin is released 😄 with this variation image argo setup will shrink considerably :)

**Comment by tico24** [comment]
renovate is fixed now.

**Comment by dennislapchenko** [comment]
@tico24 alright then i'll close this PR and wait for you to merge renovate's. hopefully wont want too long ;D 
Cheers fellas

**Comment by tico24** [comment]
It'll be a few hours probably, but should be today.

**Pull request closed without merging**
