### PR TITLE
add switch to make it possible to disable crds in helmfiles

### PR DESCRIPTION
**Pull request by joschi36**
Adding the same behaviour as in https://github.com/crumbhole/argocd-lovely-plugin/pull/563 for helmfile

### CODE REVIEW

**Comment by joschi36** [comment]
Thanks for your prompt update. Unfortunately, I can't build or test the code right now. I only eyeballed it and hoped your workflow will create a container that I can test tomorrow on my environment :sweat_smile:

**Comment by Joibel** [comment]
> Thanks for your prompt update. Unfortunately, I can't build or test the code right now. I only eyeballed it and hoped your workflow will create a container that I can test tomorrow on my environment 😅

#269 unfortunately prevents the images being made.

I've manually built you `joibel/argocd-lovely-plugin:pr610`. This is a versioned plugin, with the version being `pr610`. amd64 only.

**Comment by joschi36** [comment]
Hi @Joibel, I just tested the image and it seems to work just fine. With and without parameters.

Thank you very much for your help :+1: 

Please advise if I need to make changes.

**Review by Joibel — APPROVED** [review]
Thanks for this, looks good.

**Pull request merged**
