### PR TITLE
chore: latest argocd versions for CI

### PR DESCRIPTION
**Pull request by tico24**

### CODE REVIEW

**Comment by Joibel** [comment]
It would make sense to rename the directories to 2.4 and 2.5 at some point, to save renaming them ever again. But fine otherwise.

**Comment by tico24** [comment]
Stop talking sense

**Comment by tico24** [comment]
ah - we can't because of how the matrix works. Good. Less work for Tim.

**Comment by Joibel** [comment]
Yes boss

**Comment by tico24** [comment]
fine. I did it. Are you happy now?

**Comment by Joibel** [comment]
I really did mean 2.4 rather than 2.4.20.

**Pull request merged**
