### PR TITLE
Provide helmwave support

### PR DESCRIPTION
**Pull request by zhilyaev**
Hello folks 👋 
We have an awesome project for composing helm charts. And we would like to be part of argocd-lovely-plugin family.

### CODE REVIEW

**Comment by tico24** [comment]
Can you please raise an issue to help understand the use case for this addition?

I appreciate it's your tool but helmwave looks quite young and we haven't heard anyone requesting it.

**Comment by Joibel** [comment]
I would want to have it as a [variation](https://github.com/crumbhole/argocd-lovely-plugin/tree/main/variations).

The main Dockerfile is for tools which are required to make lovely work and have builtin support in the code. We want to keep this slim for security.

**Comment by zhilyaev** [comment]
We can continue discussion in #489 issue if you prefer that way

**Comment by Joibel** [comment]
Closing due to inactivity

**Pull request closed without merging**
